### ISSUE TITLE
Add example to all fieldtypes

### ISSUE THREAD

**Issue by goellner** [statamic/docs#17]
I just wanted to suggest, that all fieldtypes should have an example in the docs, as it is much easier to copy/paste from the docs and edit the settings than to read all the config options and figure out how the syntax is exactly. And have an anchor on them which is on the same position on every fieldtype page, so there is a common pattern with `Example/YAML` and `Config options` in the scroll-to nav.

And another suggestion: maybe have a min & max example for all the settings in a fieldtype. Maybe the maximum example has all the default options listed as well.

e.g.: minimum example
```
favorite:
  type: radio
  options:
    donuts: Donuts
    icecream: Ice Cream
    brownies: Brownies
```

e.g.: maximum example
```
favorite:
  type: radio
  inline: false
  options:
    donuts: Donuts
    icecream: Ice Cream
    brownies: Brownies
```

I used the kitchen.yaml quite a lot in the past to copy example fieldtypes.
