### ISSUE TITLE
Fieldsets Docs

### ISSUE THREAD

**Issue by janparkio** [statamic/docs#296]
New to Statamic, I've been trying to learn about this tool "Fieldsets" couldn't find anything, unfortunately, to implement it.
And how the logic works, any help?

![Screen Shot 2020-10-28 at 19 38 00](https://user-images.githubusercontent.com/9617583/97504241-42e2b380-1955-11eb-9a87-e07e45381d8a.png)

Please consider the addition of documentation too :)

**Comment by jasonvarga** [comment]
Oops, we'll fix that. For now, you can find the information at https://statamic.dev/fields

**Comment by damcclean** [comment]
Duplicate of #305.

**Comment by janparkio** [comment]
Thank you, @jasonvarga, but my issue at the moment was to implement fieldsets on blueprints, which isn't the same as fields overall. But I could figure it out.

In case someone else stumbles upon this same issue, you implement fieldsets like so:
1. Create a fieldset. Make sure the Handle is unique.
1.1. Add your fields and take note of the handles.
2. Go to the Blueprint's YAML you want to import the fieldsets to and add the 'sections' below:
```YAML
# YAML code above
sections: # sections should already exist; this is just a reference
  my_custom_field_name: # this is the name of the field you would like to use.
    display: My Custom Field Name
    fields:
      -
        import: fieldset_actual_name # this should be the name of the fieldset file on `fieldsets/fieldset_actual_name.yaml.`
        prefix: fieldset_ # the prefix you would like to use on your fields handles.
# more code below
```

A real-world example, like creating a gallery fieldset, would look like this:
```YAML
# YAML code above
sections: # sections should already exist. This is just a reference.
  gallery:
    display: Gallery
    fields:
      -
        import: gallery # in this example, there is a file on resources called `fieldsets/gallery.yaml.`
        prefix: gallery_
# more code below
```
3. Now, whatever you named your field handles, they'd be modified to the prefix we defined on the Blueprint's fieldsets fields prefix (what a mouthful). So now, going back to the Gallery example. If you made a field called  `{{ title }}` on the fieldsets. Now it can be accessed with `{{ gallery_title }}` that means [prefix + fieldset name'] on your templating area.

Note: This very same structure could be used throughout the Blueprints. I have it implemented on Bard's sets fields. Makes the blueprint look cleaner too.
