### ISSUE TITLE
Augmentation docs

### ISSUE THREAD

**Issue by edalzell** [statamic/docs#519]
I have a Users fieldtype in an entry.

Is there a way to get an array of User, instead of an array of ids, because calling augmentedValue returns:

```
^ array:1 [
  0 => "34617907-e4e7-40d2-b7b1-3d8bee4052d4"
]
```

Examples on how to handle things like would be awesome.

**Comment by jasonvarga** [comment]
You've done `$entry->augmentedValue('usersfield')`?

**Comment by edalzell** [comment]
> You've done `$entry->augmentedValue('usersfield')`?

Yes, that returns an array of ids.

**Comment by jasonvarga** [comment]
Is it definitely a `users` fieldtype?

**Comment by edalzell** [comment]
```
      -
        handle: users
        field:
          mode: select
          display: Users
          type: users
          icon: users
          listable: hidden
```
